# Generated by Django 4.2 on 2024-09-10 12:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pupils', '0004_alter_pupil_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_period', models.DateField(verbose_name='')),
                ('end_period', models.DateField(default=datetime.date.today, verbose_name='')),
                ('pupil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_pupil', to='pupils.pupil', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Отчёт',
                'verbose_name_plural': 'Отчёты',
                'db_table': 'reports',
                'ordering': ('-id',),
            },
        ),
    ]
