# Generated by Django 4.2 on 2024-09-14 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='end_period',
            field=models.DateField(default=datetime.date.today, verbose_name='Конец периода'),
        ),
        migrations.AlterField(
            model_name='report',
            name='start_period',
            field=models.DateField(verbose_name='Начало периода'),
        ),
    ]
