# Generated by Django 4.2 on 2024-08-27 16:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Имя')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('price_per_hour', models.PositiveSmallIntegerField(default=0, verbose_name='Цена за час урока')),
                ('class_counter', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(11)], verbose_name='Класс')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен ли')),
                ('skype_only', models.BooleanField(default=False, verbose_name='Занятия только по Skype')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Добавил')),
                ('subjects', models.ManyToManyField(blank=True, null=True, related_name='subjects', to='subjects.subjects', verbose_name='Предметы')),
            ],
        ),
    ]
