# Generated by Django 4.2 on 2024-08-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
        ('pupils', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pupil',
            options={'ordering': ('id',), 'verbose_name': 'Ученик', 'verbose_name_plural': 'Ученики'},
        ),
        migrations.AlterField(
            model_name='pupil',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='subjects.subjects', verbose_name='Предметы'),
        ),
        migrations.AlterModelTable(
            name='pupil',
            table='pupil',
        ),
    ]
