# Generated by Django 4.2 on 2024-08-27 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pupils', '0002_alter_pupil_options_alter_pupil_subjects_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pupil',
            table='pupils',
        ),
    ]
