# Generated by Django 4.2 on 2024-09-06 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pupils', '0003_alter_pupil_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pupil',
            options={'ordering': ('-id',), 'verbose_name': 'Ученик', 'verbose_name_plural': 'Ученики'},
        ),
    ]
