# Generated by Django 4.2 on 2024-09-06 09:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        ('pupils', '0004_alter_pupil_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Дата проведения урока')),
                ('lesson_duration', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(1, 'Слишком короткий урок'), django.core.validators.MaxValueValidator(2, 'Слишком долгий урок')], verbose_name='Продолжительность урока')),
                ('money_recived', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Денег заработано')),
                ('pupil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pupils.pupil', verbose_name='Ученик')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subjects', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'db_table': 'lessons',
                'ordering': ('-datetime', '-id'),
            },
        ),
    ]
