# Generated by Django 4.2 on 2024-09-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='money_recived',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Денег заработано'),
        ),
    ]
